sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_65b05ac2d55e_key -iv $encrypted_65b05ac2d55e_iv
  -in cs.json.enc -out cs.json -d

deploy:
  provider: gae
  keyfile: cs.json
  project: docker-flow
  edge: true
  install_sdk: true
  on: main